
%% Step 1: Import EEG data
load('D:\1_Work\4_Work_2024\PSD_Data\msEEG02.mat');
load('D:\1_Work\4_Work_2024\PSD_Data\adEEG02.mat');

allEEG = msEEG02(1);
dataType = 'MS'; 

%% Step 2: Extract Parameters, Chart and Table

peSettings = struct(...
                'freqsRangePe',[4.0, 16] ,...
                'peak_width_limits', [0.05, 20], ... 
                'max_n_peaks', 1, ... 
                'min_peak_height', 0.01, ...
                'peak_threshold', -5, ...
                'aperiodic_mode', 'fixed', ...
                'verbose', false); 
apeSettings = struct(...
                'freqsRangeApe', [0.5, 40], ...
                'peak_width_limits', [0.05, 20], ...
                'max_n_peaks', Inf, ...
                'min_peak_height', 0.1, ...
                'peak_threshold', -10, ...
                'aperiodic_mode', 'fixed', ...
                'verbose', false);                     
            
pgr = PatientGroupResultV2(allEEG, dataType, 'cGT', 'settings', peSettings, apeSettings);




